### ISSUE TITLE
Adding alternative routes for Directions

### ISSUE THREAD

**Issue by nickbroom3** [GIScience/openrouteservice-js#29]
Hi,

When I try and add alternative_routes as an argument to Directions.calculate I get the following error: 
An error occured: Error: ValidationError: "alternative_routes" is not allowed. Although alternative_routes is a supported field in the API Playground (https://openrouteservice.org/dev/#/api-docs/v2/directions/{profile}/json/post). Does openrouteservice-js support alternative routes for finding directions between two points>

**Comment by amoncaldas** [comment]
Hey @nickbromm3

Sorry for the late reply. Not sure if it still useful or if you have already solved it.

I think that when you tried it we still had the client side parameters validation. So the library was validating the parameters before sending them to the API. As it started to be a burden (due to API new parameters) we decided to remove this pre-request validation and rely only on the API validation.
Since we removed this library validation all the parameters accepted by the API are passed and then the alternative_routes is also accepted. It is being used on our new maps client (still in beta).

Cheers,
